### ISSUE TITLE
Error in nodejs package v0.12.0

### ISSUE THREAD

**Issue by danielpinto8zz6** [iilei/traduora-cli#12]
Hi,
In v0.12.0 the package has not been updated in getAuthToken it still has wrong method: `    return response.data.data.accessToken;
`
can you make a new release? the github release is fine

**Comment by Jekiwijaya** [comment]
@iilei

**Comment by iilei** [comment]
Please try traduora-cli@0.12.0-rebuilt @danielpinto8zz6

**Comment by danielpinto8zz6** [comment]
@iilei thank you
